import React from "react";
export const compras = [
  {
    key: "1",
    autor: "Rodrigo Espindola",
    descripcion: "asdasdasdasdasdasdasdasdasdasdasdasd",
    tarjeta: "Visa",
    detalleTarjeta:"MercadoLibre*MercadoPago",
    montoTotal: "$500.000",
    fechaCompra: "20/03/2024",
    cantidadCuotas: "6",
    montoCuota: "$90.000",
    cuotasRestantes: "4"
  },
  {
    key: "2",
    autor: "Rodrigo Espindola",
    descripcion: "Televisor",
    tarjeta: "Visa",
    detalleTarjeta:"MercadoLibre*MercadoPago",
    montoTotal: "$500.000",
    fechaCompra: "20/03/2024",
    cantidadCuotas: "6",
    montoCuota: "$90.000",
    cuotasRestantes: "4"
  },
  {
    key: "2",
    autor: "Rodrigo Espindola",
    descripcion: "Televisor",
    tarjeta: "Visa",
    detalleTarjeta:"MercadoLibre*MercadoPago",
    montoTotal: "$500.000",
    fechaCompra: "20/03/2024",
    cantidadCuotas: "6",
    montoCuota: "$90.000",
    cuotasRestantes: "4"
  },
  {
    key: "2",
    autor: "Rodrigo Espindola",
    descripcion: "Televisor",
    tarjeta: "Visa",
    detalleTarjeta:"MercadoLibre*MercadoPago",
    montoTotal: "$500.000",
    fechaCompra: "20/03/2024",
    cantidadCuotas: "6",
    montoCuota: "$90.000",
    cuotasRestantes: "4"
  },
  {
    key: "2",
    autor: "Rodrigo Espindola",
    descripcion: "Televisor",
    tarjeta: "Visa",
    detalleTarjeta:"MercadoLibre*MercadoPago",
    montoTotal: "$500.000",
    fechaCompra: "20/03/2024",
    cantidadCuotas: "6",
    montoCuota: "$90.000",
    cuotasRestantes: "4"
  },
  {
    key: "2",
    autor: "Rodrigo Espindola",
    descripcion: "Televisor",
    tarjeta: "Visa",
    detalleTarjeta:"MercadoLibre*MercadoPago",
    montoTotal: "$500.000",
    fechaCompra: "20/03/2024",
    cantidadCuotas: "6",
    montoCuota: "$90.000",
    cuotasRestantes: "4"
  },
  {
    key: "2",
    autor: "Rodrigo Espindola",
    descripcion: "Televisor",
    tarjeta: "Visa",
    detalleTarjeta:"MercadoLibre*MercadoPago",
    montoTotal: "$500.000",
    fechaCompra: "20/03/2024",
    cantidadCuotas: "6",
    montoCuota: "$90.000",
    cuotasRestantes: "4"
  },
  {
    key: "2",
    autor: "Rodrigo Espindola",
    descripcion: "Televisor",
    tarjeta: "Visa",
    detalleTarjeta:"MercadoLibre*MercadoPago",
    montoTotal: "$500.000",
    fechaCompra: "20/03/2024",
    cantidadCuotas: "6",
    montoCuota: "$90.000",
    cuotasRestantes: "4"
  },
  ,
  {
    key: "2",
    autor: "Rodrigo Espindola",
    descripcion: "Televisor",
    tarjeta: "Visa",
    detalleTarjeta:"MercadoLibre*MercadoPago",
    montoTotal: "$500.000",
    fechaCompra: "20/03/2024",
    cantidadCuotas: "6",
    montoCuota: "$90.000",
    cuotasRestantes: "4"
  },
  {
    key: "2",
    autor: "Rodrigo Espindola",
    descripcion: "Televisor",
    tarjeta: "Visa",
    detalleTarjeta:"MercadoLibre*MercadoPago",
    montoTotal: "$500.000",
    fechaCompra: "20/03/2024",
    cantidadCuotas: "6",
    montoCuota: "$90.000",
    cuotasRestantes: "4"
  },
  {
    key: "2",
    autor: "Rodrigo Espindola",
    descripcion: "Televisor",
    tarjeta: "Visa",
    detalleTarjeta:"MercadoLibre*MercadoPago",
    montoTotal: "$500.000",
    fechaCompra: "20/03/2024",
    cantidadCuotas: "6",
    montoCuota: "$90.000",
    cuotasRestantes: "4"
  },
  {
    key: "2",
    autor: "Rodrigo Espindola",
    descripcion: "Televisor",
    tarjeta: "Visa",
    detalleTarjeta:"MercadoLibre*MercadoPago",
    montoTotal: "$500.000",
    fechaCompra: "20/03/2024",
    cantidadCuotas: "6",
    montoCuota: "$90.000",
    cuotasRestantes: "4"
  },
  {
    key: "2",
    autor: "Rodrigo Espindola",
    descripcion: "Televisor",
    tarjeta: "Visa",
    detalleTarjeta:"MercadoLibre*MercadoPago",
    montoTotal: "$500.000",
    fechaCompra: "20/03/2024",
    cantidadCuotas: "6",
    montoCuota: "$90.000",
    cuotasRestantes: "4"
  },
  {
    key: "2",
    autor: "Rodrigo Espindola",
    descripcion: "Televisor",
    tarjeta: "Visa",
    detalleTarjeta:"MercadoLibre*MercadoPago",
    montoTotal: "$500.000",
    fechaCompra: "20/03/2024",
    cantidadCuotas: "6",
    montoCuota: "$90.000",
    cuotasRestantes: "4"
  },
  {
    key: "2",
    autor: "Rodrigo Espindola",
    descripcion: "Televisor",
    tarjeta: "Visa",
    detalleTarjeta:"MercadoLibre*MercadoPago",
    montoTotal: "$500.000",
    fechaCompra: "20/03/2024",
    cantidadCuotas: "6",
    montoCuota: "$90.000",
    cuotasRestantes: "4"
  },
  ,
  {
    key: "2",
    autor: "Rodrigo Espindola",
    descripcion: "Televisor",
    tarjeta: "Visa",
    detalleTarjeta:"MercadoLibre*MercadoPago",
    montoTotal: "$500.000",
    fechaCompra: "20/03/2024",
    cantidadCuotas: "6",
    montoCuota: "$90.000",
    cuotasRestantes: "4"
  },
  {
    key: "2",
    autor: "Rodrigo Espindola",
    descripcion: "Televisor",
    tarjeta: "Visa",
    detalleTarjeta:"MercadoLibre*MercadoPago",
    montoTotal: "$500.000",
    fechaCompra: "20/03/2024",
    cantidadCuotas: "6",
    montoCuota: "$90.000",
    cuotasRestantes: "4"
  },
  {
    key: "2",
    autor: "Rodrigo Espindola",
    descripcion: "Televisor",
    tarjeta: "Visa",
    detalleTarjeta:"MercadoLibre*MercadoPago",
    montoTotal: "$500.000",
    fechaCompra: "20/03/2024",
    cantidadCuotas: "6",
    montoCuota: "$90.000",
    cuotasRestantes: "4"
  },
  {
    key: "2",
    autor: "Rodrigo Espindola",
    descripcion: "Televisor",
    tarjeta: "Visa",
    detalleTarjeta:"MercadoLibre*MercadoPago",
    montoTotal: "$500.000",
    fechaCompra: "20/03/2024",
    cantidadCuotas: "6",
    montoCuota: "$90.000",
    cuotasRestantes: "4"
  },
  {
    key: "2",
    autor: "Rodrigo Espindola",
    descripcion: "Televisor",
    tarjeta: "Visa",
    detalleTarjeta:"MercadoLibre*MercadoPago",
    montoTotal: "$500.000",
    fechaCompra: "20/03/2024",
    cantidadCuotas: "6",
    montoCuota: "$90.000",
    cuotasRestantes: "4"
  },
  {
    key: "2",
    autor: "Rodrigo Espindola",
    descripcion: "Televisor",
    tarjeta: "Visa",
    detalleTarjeta:"MercadoLibre*MercadoPago",
    montoTotal: "$500.000",
    fechaCompra: "20/03/2024",
    cantidadCuotas: "6",
    montoCuota: "$90.000",
    cuotasRestantes: "4"
  },
  {
    key: "2",
    autor: "Rodrigo Espindola",
    descripcion: "Televisor",
    tarjeta: "Visa",
    detalleTarjeta:"MercadoLibre*MercadoPago",
    montoTotal: "$500.000",
    fechaCompra: "20/03/2024",
    cantidadCuotas: "6",
    montoCuota: "$90.000",
    cuotasRestantes: "4"
  },
  
  
  
];
